services:
  orchestrator:
    image: ghcr.io/linuxfight/yndxcalcdistapi-orchestrator:master
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9090/startupz"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "9090:9090"
    env_file:
      - .env
    restart: unless-stopped
  agent:
    image: ghcr.io/linuxfight/yndxcalcdistapi-agent:master
    env_file:
      - .env
    depends_on:
      orchestrator:
        condition: service_healthy
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "databases 3" >> /usr/local/etc/redis/redis.conf &&  # <-- ADD THIS LINE
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  redis-data: